### ISSUE TITLE
Timeouts in different places

### ISSUE THREAD

**Issue by roarkmccolgan** [graze/telnet-client#20]
Hi Again.

We're connecting to a server and doing the same sequence of commands and interactions, I've been receiving a number of timeout exceptions but they are in different places of the telnet client.
```
//Timeout on this line, once in the last 24hrs. TelnetClient.php at line 223
if (in_array($character, [$this->NULL, $this->DC1])) {
    break;
}
```
```
//Timeout on this method, once in the last 24hrs. Socket.php at line 243
public function read($length, $type = PHP_BINARY_READ) {
```
```
//Timeout on this method, 3 times in the last 24hrs. TelnetClient.php at line 239
if ($this->promptMatcher->isMatch($this->promptError, $buffer, $this->lineEnding)) {
```
```
//Timeout on this method, 2 times in the last 24hrs. PromptMatcher.php at line 39
if (!is_null($lineEnding) && substr($subject, -1 * strlen($lineEnding)) != $lineEnding) {
```
```
//Timeout on this method, 5 times in the last 24hrs. Socket.php at line 245
$data = @socket_read($this->resource, $length, $type);
```
Now I'm pretty sure because of how random it is it must be something to do with the host server but wanted to know if you've ever come across this or how I could handle it?
It usually happens after a successful interaction so do I need to close the connection manually? You've already doing that in the destructor though

Thanks for any help you can provide.

**Comment by john-n-smith** [comment]
Hi,

Does your current timeout allow enough time for the work to be done? You may find that you have it set too low.

The timeouts may be caused by network disruption. Depending on the network you're communicating over (internet, local) and the frequency the process is running, connectivity issues may be transient and are to be expected. If that's the case, you could make your process more resilient by catching the exceptions and retrying a few times. It's often useful to implement a retry schedule that utilises an exponential backoff when dealing with connectivity issues.
